---
# tasks file for ansible-role-argus-radium

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ argus_radium_log_dir }}"
    mode: 0755
    owner: "{{ argus_user}}"
    group: "{{ argus_group }}"
    state: directory
  notify: Restart radium

- name: Create radium.conf
  template:
    src: radium.conf.j2
    dest: "{{ argus_radium_conf_file }}"
  notify: Restart radium

- command: test -f /usr/local/bin/radium
  changed_when: false


- name: Start radium
  service:
    name: "{{ argus_radium_service }}"
    enabled: true
    state: started

- command: test -f /usr/local/bin/radium
  changed_when: false
