---
# tasks file for ansible-role-argus-radium

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create argus_radium_group
  group:
    name: "{{ argus_radium_group }}"
    gid: "{{ argus_radium_group_gid }}"

- name: Create argus_radium_user
  user:
    name: "{{ argus_radium_user }}"
    group: "{{ argus_radium_group }}"
    home: "{{ argus_radium_user_home }}"
    shell: "{{ argus_radium_user_shell }}"
    uid: "{{ argus_radium_user_uid }}"
    comment: "{{ argus_radium_user_comment }}"
    createhome: no
    state: present

- name: Create log directory
  file:
    path: "{{ argus_radium_log_dir }}"
    mode: 0755
    owner: "{{ argus_radium_user}}"
    group: "{{ argus_radium_group }}"
    state: directory
  notify: Restart radium

- name: Create radium.conf
  template:
    src: radium.conf.j2
    dest: "{{ argus_radium_conf_file }}"
  notify: Restart radium

- name: Start radium
  service:
    name: "{{ argus_radium_service }}"
    enabled: true
    state: started
    args: "{% if ansible_os_family == 'OpenBSD' %}{{ argus_radium_flags }}{% endif %}"
